//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class cvEntities : DbContext
    {
        public cvEntities()
            : base("name=cvEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arbeidserfaring> Arbeidserfaring { get; set; }
        public virtual DbSet<CVVersjon> CVVersjon { get; set; }
        public virtual DbSet<DatabasesystemListe> DatabasesystemListe { get; set; }
        public virtual DbSet<Kompetanse> Kompetanse { get; set; }
        public virtual DbSet<Medlem> Medlem { get; set; }
        public virtual DbSet<OperativsystemListe> OperativsystemListe { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<ProgrammeringsspråkListe> ProgrammeringsspråkListe { get; set; }
        public virtual DbSet<Prosjekt> Prosjekt { get; set; }
        public virtual DbSet<RammeverkListe> RammeverkListe { get; set; }
        public virtual DbSet<ServersideListe> ServersideListe { get; set; }
        public virtual DbSet<SpråkListe> SpråkListe { get; set; }
        public virtual DbSet<Utdannelse> Utdannelse { get; set; }
        public virtual DbSet<WebTeknologiListe> WebTeknologiListe { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
    }
}
