//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCV.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CvPortalEntities : DbContext
    {
        public CvPortalEntities()
            : base("name=CvPortalEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Arbeidserfaring> Arbeidserfaring { get; set; }
        public virtual DbSet<CVVersjon> CVVersjon { get; set; }
        public virtual DbSet<Innstillinger> Innstillinger { get; set; }
        public virtual DbSet<Kompetanse> Kompetanse { get; set; }
        public virtual DbSet<ListeKatalog> ListeKatalog { get; set; }
        public virtual DbSet<Medlem> Medlem { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Prosjekt> Prosjekt { get; set; }
        public virtual DbSet<TekniskProfil> TekniskProfil { get; set; }
        public virtual DbSet<Utdannelse> Utdannelse { get; set; }
    }
}
