//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medlem
    {
        public int MedlemId { get; set; }
        public string Rolle { get; set; }
        public short Start { get; set; }
        public short Slutt { get; set; }
        public int ProsjektProsjektId { get; set; }
        public int Person_PersonId { get; set; }
    
        public virtual Person Person { get; set; }
        public virtual Prosjekt Prosjekt { get; set; }
    }
}
