//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GeoCV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TekniskProfil
    {
        public int TekniskProfilId { get; set; }
        public string Navn { get; set; }
        public string Elementer { get; set; }
        public int ProsjektProsjektId { get; set; }
    
        public virtual Prosjekt Prosjekt { get; set; }
    }
}
